### PR TITLE
[ISSUE-147]: Change messages and input on confirm registration page

### PR DESCRIPTION
**Pull request by Lightness322**
1. Task's name:
Text inconsistency. Should be "confirm registration" instead of "confirm password"

2. Developer's full name:
Mikhail Dyubkov

3. Changes:
- change input on confirmation page, now it allows type only numbers and auto-add hyphens
- change required input message on confirmation page
- change title on confirmation page
- change custom Input props to make possible work with controlled input

### CODE REVIEW

**Comment by freecree** [comment]
I've got some unexpected behavior when trying to register. I filled inputs  and after I clicked register, I had this errors although I filled inputs correctly. Can you check it, please
image

**Review by freecree — COMMENTED** [review]
I've got some unexpected behavior when trying to register. I filled inputs  and after I clicked register, I had this errors although I filled inputs correctly. Can you check it, please
image

**Comment by Lightness322** [comment]
> I've got some unexpected behavior when trying to register. I filled inputs and after I clicked register, I had this errors although I filled inputs correctly. Can you check it, please image

FIXED

**Review by anksuunamun — COMMENTED** [review]
После того как ты добавил автоматическое удаление неподходящих символов в поле для кода подтверждения регистрации возник баг с фокусом: если где-то в поле (кроме после последнего символа) ввести символ - после появления нового символа курсор прыгает в конец поля

**Review by freecree — APPROVED** [review]

**Review by freecree — APPROVED** [review]

**Review by anksuunamun — APPROVED** [review]

**Review by Sunagatov — APPROVED** [review]

**Pull request merged**
